language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env: STORM_PACKAGE=storm
    - python: 2.7
      env: STORM_PACKAGE=storm-legacy
    - python: 3.4
      env: STORM_PACKAGE=storm
    - python: 3.4
      env: STORM_PACKAGE=storm-legacy
    - python: 3.5
      env: STORM_PACKAGE=storm
    - python: 3.5
      env: STORM_PACKAGE=storm-legacy
    - python: 3.6
      env: STORM_PACKAGE=storm
    - python: 3.6
      env: STORM_PACKAGE=storm-legacy
    - python: 3.7
      env: STORM_PACKAGE=storm
    - python: 3.7
      env: STORM_PACKAGE=storm-legacy
    - python: 3.8
      env: STORM_PACKAGE=storm
    - python: 3.8
      env: STORM_PACKAGE=storm-legacy

install:
    - pip install -r requirements.txt
    - pip install $STORM_PACKAGE

script:
    - pytest
